"""Generated-file detection for the zero-config report.

Generated code (Fern/OpenAPI clients, protobuf stubs, Django migrations) is
reported but not flagged: the report banner counts it, the unused lane treats
generated files as reference-only sources, and duplicate groups confined to
generated files are labeled generator output rather than copy-paste.
"""

from __future__ import annotations

from wcmatch import glob as wcglob

from konpy.core._filesystem_base import _GLOB_FLAGS
from konpy.core.filesystem import FileSystem

_HEADER_LINES = 12
# High-specificity markers count anywhere in the header, docstring banners
# included: `@generated` is the cross-tool convention and OpenAPI Generator
# stamps its URL into a module docstring.
_STRONG_MARKERS = (
    "@generated",
    "openapi-generator",
)
# Generic phrases only count inside `#` comment lines: hand-written docstring
# prose ("utilities for auto-generated request IDs — do not edit the format")
# must not mark a file. Real generator banners (Fern, protoc, Django, gRPC)
# are `#` comments.
_COMMENT_MARKERS = (
    "auto-generated",
    "autogenerated",
    "automatically generated",
    "generated by",
    "do not edit",
    "do not modify",
)

FERNIGNORE_PATH = ".fernignore"


def is_generated_source(source: str) -> bool:
    """Check the first few lines of `source` for a code-generator banner."""
    for line in source.splitlines()[:_HEADER_LINES]:
        lowered = line.lower()
        if any(marker in lowered for marker in _STRONG_MARKERS):
            return True
        if lowered.lstrip().startswith("#") and any(
            marker in lowered for marker in _COMMENT_MARKERS
        ):
            return True
    return False


def apply_fernignore(file_system: FileSystem, generated: set[str]) -> set[str]:
    """Drop `.fernignore`-listed paths from `generated`.

    Fern stamps its banner on every file it emits, but files listed in
    `.fernignore` are the ones Fern must never overwrite — they are
    hand-maintained even when they still carry a (stale) banner.
    """
    if not generated:
        return generated
    patterns = _fernignore_patterns(file_system)
    if not patterns:
        return generated
    # gitignore-style: a bare directory entry exempts everything under it.
    expanded: list[str] = []
    for pattern in patterns:
        cleaned = pattern.rstrip("/")
        expanded.extend((cleaned, f"{cleaned}/**"))
    return {
        path
        for path in generated
        if not wcglob.globmatch(path, expanded, flags=_GLOB_FLAGS)
    }


def _fernignore_patterns(file_system: FileSystem) -> tuple[str, ...]:
    if not file_system.file_exists(FERNIGNORE_PATH):
        return ()
    try:
        text = file_system.read_file(FERNIGNORE_PATH)
    except OSError:
        return ()
    return tuple(
        stripped
        for line in text.splitlines()
        if (stripped := line.strip()) and not stripped.startswith("#")
    )


__all__ = [
    "FERNIGNORE_PATH",
    "apply_fernignore",
    "is_generated_source",
]
