"""Tests for generated-file detection (`konpy.core._report_generated`).

Generator-banner strings below are built by concatenation so this test file's
own header never contains a marker verbatim — otherwise the report would count
the test suite itself as generated (see the self-check test at the bottom).
"""

from __future__ import annotations

from pathlib import Path

from konpy.core._report_generated import apply_fernignore, is_generated_source
from konpy.core.filesystem import FakeFileSystem

FERN_BANNER = "# This file was auto-" + "generated by Fern from our API Definition.\n"
PROTOBUF_BANNER = "# Generated by" + " the protocol buffer compiler.  DO NOT" + " EDIT!\n"
DJANGO_BANNER = "# Generated by" + " Django 4.2.7 on 2023-11-14 09:30\n"
AT_GENERATED = "@" + "generated"


class TestIsGeneratedSource:
    def test_fern_banner_is_generated(self) -> None:
        assert is_generated_source(FERN_BANNER + "\nx = 1\n")

    def test_protobuf_do_not_edit_is_generated(self) -> None:
        source = "# -*- coding: utf-8 -*-\n" + PROTOBUF_BANNER + "x = 1\n"
        assert is_generated_source(source)

    def test_django_migration_comment_is_generated(self) -> None:
        source = DJANGO_BANNER + "\nfrom django.db import migrations\n"
        assert is_generated_source(source)

    def test_at_generated_in_docstring_is_generated(self) -> None:
        source = f'"""Client stubs.\n\n{AT_GENERATED} by protoc-gen-python.\n"""\nx = 1\n'
        assert is_generated_source(source)

    def test_docstring_prose_mentioning_generated_by_is_not_marked(self) -> None:
        # Generic markers only count in `#` comment lines: a module docstring
        # describing "reports generated by the engine" is hand-written prose.
        source = '"""Rendering for reports generated by the analysis engine."""\n\nx = 1\n'
        assert not is_generated_source(source)

    def test_docstring_prose_with_generic_banner_phrases_is_not_marked(self) -> None:
        # "auto-generated"/"do not edit" in docstring prose describe the
        # module's subject, not its provenance.
        source = (
            '"""Utilities for auto-' 'generated request IDs.\n'
            "\n"
            "Do not" ' edit the ID format without bumping the schema version.\n'
            '"""\n'
            "x = 1\n"
        )
        assert not is_generated_source(source)

    def test_openapi_generator_docstring_banner_is_marked(self) -> None:
        source = '"""My API client.\n\nGenerated by: https://openapi-generator.tech\n"""\n'
        assert is_generated_source(source)

    def test_marker_beyond_header_window_is_ignored(self) -> None:
        source = "\n".join(f"x{i} = {i}" for i in range(20)) + "\n" + FERN_BANNER
        assert not is_generated_source(source)

    def test_plain_file_is_not_generated(self) -> None:
        assert not is_generated_source('"""A hand-written module."""\n\nx = 1\n')

    def test_this_test_file_is_not_marked_generated(self) -> None:
        # The concatenation trick above must keep every marker out of this
        # file's own header window; a refactor that moves a banner literal
        # into the first lines would silently inflate the dogfood's count.
        assert not is_generated_source(Path(__file__).read_text(encoding="utf-8"))


class TestApplyFernignore:
    def test_fernignore_listed_paths_are_hand_maintained(self) -> None:
        file_system = FakeFileSystem(
            contents={
                ".fernignore": (
                    "# Specify files that shouldn't be modified by Fern\n"
                    "\n"
                    "src/pkg/query_encoder.py\n"
                )
            }
        )
        generated = {"src/pkg/client.py", "src/pkg/query_encoder.py"}

        assert apply_fernignore(file_system, generated) == {"src/pkg/client.py"}

    def test_bare_directory_entry_exempts_nested_files(self) -> None:
        file_system = FakeFileSystem(contents={".fernignore": "custom\n"})
        generated = {"custom/foo.py", "custom/nested/bar.py", "src/client.py"}

        assert apply_fernignore(file_system, generated) == {"src/client.py"}

    def test_no_fernignore_leaves_set_unchanged(self) -> None:
        file_system = FakeFileSystem(contents={"src/mod.py": "x = 1\n"})
        generated = {"src/mod.py"}

        assert apply_fernignore(file_system, generated) == generated
